version: "3.8"

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile_KeyCloak&Provider
    command: start-dev
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: root
      KC_DB_URL: jdbc:postgresql://db:5432/gazon_db
      KC_DB_PASSWORD: root
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: gazon_db
      KC_DB_URL_HOST: db
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: 'postgres:12.12'
    environment:
      POSTGRES_DB: gazon_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: "exit 0"
    ports:
      - "5431:5432"
