version: "3.8"

services:
  app:
    image: quay.io/keycloak/keycloak:23.0.1
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_svr
      KC_DB_URL_DATABASE: gazon_db
      KC_DB_PASSWORD: root
      KC_DB_USERNAME: root
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"
    depends_on:
      postgres_svr:
        condition: service_healthy
    networks:
      network_sso:
        ipv4_address: "10.0.0.2"
#    volumes:
#      - /out/artifacts/custom_user_provider_jar/custom-user-provider.jar:/opt/jboss/keycloak/providers/custom-user-provider.jar


  postgres_svr:
    image: 'postgres:12.12'
    environment:
      POSTGRES_DB: gazon_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: "exit 0"
    ports:
      - "5431:5432"
    networks:
      network_sso:
        ipv4_address: "10.0.0.3"
networks:
  network_sso:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"