apiVersion: v1
kind: ConfigMap
metadata:
  name: gazon-config-map
data:
  application.yml: |
    spring:
      application:
        name: gazon-service
      profiles:
        active: dev
      cache:
        type: SIMPLE

      liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml

      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://db-service:5432/postgres
        username: root
        password: root
        hikari:
          leak-detection-threshold: 60000
          maximum-pool-size: 20

      jpa:
        show-sql: false
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            storage_engine: innodb
            current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
            format_sql: true
            jdbc:
              time_zone: Europe/Moscow

      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
