spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 563006777026-9l2ulo7t8m7tt4sooaod4bbftdr4urdb.apps.googleusercontent.com
            client-secret: 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
            client-name: google
            scope:
              - email
              - profile
              - openid

  application:
    name: security-service

  liquibase:
    enabled: false


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gazon_db?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
    username: root
    password: root
    hikari:
      leak-detection-threshold: 60000
      maximum-pool-size: 20

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        storage_engine: innodb
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        jdbc:
          time_zone: Europe/Moscow

jwt_secret: d935b276bd281799fd1fcb79a12c6633b1a3688871c493190b29b6cd53c57971

server:
  port: 8083
  servlet:
    session:
      timeout: -1

#app:
#  feign:
#    config:
#      name: api-gateway
#      url: http://localhost:8081
#
#feign:
#  okhttp:
#    enabled: true

springfox:
  documentation:
    auto-startup: false