server:
  port: 8080
  servlet:
    session:
      timeout: -1

spring:
  application:
    name: gazon-service
  profiles:
    active: dev
  cache:
    type: SIMPLE

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gazon_db?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
    username: root
    password: root
    hikari:
      leak-detection-threshold: 60000
      maximum-pool-size: 20

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        storage_engine: innodb
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        jdbc:
          time_zone: Europe/Moscow

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

vaadin:
  excludeUrls: /swagger-ui/**